### ISSUE TITLE
Error after adding MX record

### ISSUE THREAD

**Issue by wnukadrian** [Aplyca/terraform-aws-route53#3]
Hello, how to resolve error with MX record?

Simply example:

```
module "r53_domain" {
  source  = "source"

  description = "Description"
  domain = "domain.com"
  records = {
    names = [
      ""
    ]
    types = [
      "MX"
    ]
    ttls = [
      "10"
    ]
    values = [
      "aspmx3.googlemail.com"
    ]
  }
}
```

And I receive a error like this:

`Error: [ERR]: Error building changeset: InvalidChangeBatch: [Invalid Resource Record: FATAL problem: MXRRDATANotTwoFields (MX record doesn't have 2 fields)`

**Comment by wnukadrian** [comment]
Okay, record MX must have priority on top :)

**Comment by mauricios** [comment]
@a-w11 Thanks for using this module. Did you find a bug with your use case?

**Comment by wnukadrian** [comment]
@mauricios, of course. It's my fault beacuse I use mailserver without priority. It must be like this:
```
    values = [
      "10 aspmx3.googlemail.com"
    ]
```

**Comment by abdennour** [comment]
Thanks @a-w11  you saved my day

**Comment by Wanderson304** [comment]
Wow!  you saved my day!
